baseURL = "/"
disableKinds = ["taxonomy", "term"]
languageCode = "en-en"
staticDir = ["dist", "static"]
title = "ek|photos"

[imaging]
quality = 100

[imaging.exif]
disableDate = true
includeFields = "(ApertureValue|FocalLength|ExposureTime|ISOSpeedRatings|Model|LensModel)"
