baseURL = "/"
disableKinds = ["taxonomy", "term"]
languageCode = "en-en"
staticDir = "dist"
title = "ek|photos"

[imaging]
quality = 90

[imaging.exif]
disableDate = true
includeFields = "(ApertureValue|FocalLength|ExposureTime|ISOSpeedRatings|Model|LensModel)"
