baseURL = "http://example.org/"
languageCode = "en-en"
theme = "default"
title = "ek|photos"

[imaging]
quality = 85

[imaging.exif]
disableDate = true
includeFields = "(ApertureValue|FocalLength|ExposureTime|ISOSpeedRatings|Model|LensModel)"
